name: ✅ Lint & test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: mdarocha/nix-magic-setup@fbeadb287d13c1f3a3c2ccd9b7fb0f6201300997 # v1.3.0
        with:
          free-up-all-storage: true

      - run: devenv test
      - run: nix flake check --impure
